# Generated by Django 3.0.3 on 2020-05-07 13:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Landlord_Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identification', models.FileField(blank=True, null=True, upload_to='')),
                ('image', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('is_landlord', models.BooleanField(choices=[(True, 'Landlord'), (False, 'Tenant')], default=True)),
                ('street1', models.CharField(max_length=20, null=True)),
                ('street2', models.CharField(max_length=20, null=True)),
                ('county', models.CharField(max_length=20, null=True)),
                ('postCode', models.CharField(max_length=20, null=True)),
                ('landlord', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tenant_Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identification', models.FileField(blank=True, null=True, upload_to='docs')),
                ('image', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('is_landlord', models.BooleanField(choices=[(True, 'Landlord'), (False, 'Tenant')], default=False)),
                ('salary', models.FloatField(null=True)),
                ('salaryDocument', models.FileField(blank=True, null=True, upload_to='docs')),
                ('references', models.FileField(blank=True, null=True, upload_to='docs')),
                ('savingsDocument', models.FileField(blank=True, null=True, upload_to='docs')),
                ('is_hap', models.NullBooleanField(default=False)),
                ('hapDocument', models.FileField(blank=True, null=True, upload_to='docs')),
                ('both_salary', models.IntegerField(default=None, null=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tenant_Reviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField()),
                ('stars', models.IntegerField(default=5)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('landlord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Landlord_Profile')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Tenant_Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Guarantor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('g_salary', models.FloatField(null=True)),
                ('g_salaryDoc', models.FileField(blank=True, null=True, upload_to='docs')),
                ('g_confirmation', models.FileField(blank=True, null=True, upload_to='docs')),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.Tenant_Profile')),
            ],
        ),
    ]
