# Generated by Django 3.0.3 on 2020-02-05 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_profile_tenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='usertype',
            field=models.BooleanField(default=0),
        ),
    ]
