# Generated by Django 3.0.3 on 2020-02-05 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_profile_usertype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='usertype',
            field=models.BooleanField(choices=[(1, 'Landlord'), (2, 'Tenant')]),
        ),
    ]
