# Generated by Django 3.0.3 on 2020-02-06 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20200206_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='usertype',
            field=models.BooleanField(choices=[(1, 'Landlord'), (2, 'Tenant')], default='Tenant'),
        ),
    ]
