# Generated by Django 3.0.3 on 2020-02-06 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20200206_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='usertype',
            field=models.BooleanField(choices=[(True, 'Landlord'), (False, 'Tenant')], default=False),
        ),
    ]
