# Generated by Django 3.0.2 on 2020-02-13 22:57

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0017_profile_usertype'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profile',
            new_name='Tenant_Profile',
        ),
    ]
