# Generated by Django 3.0.2 on 2020-02-13 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_auto_20200213_2257'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tenant_profile',
            old_name='usertype',
            new_name='is_landlord',
        ),
    ]
