# Generated by Django 3.0.2 on 2020-02-13 23:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0019_auto_20200213_2301'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant_profile',
            name='is_hap',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='tenant_profile',
            name='salary',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='tenant_profile',
            name='salary_doc',
            field=models.FilePathField(null=True),
        ),
        migrations.AddField(
            model_name='tenant_profile',
            name='savings',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='tenant_profile',
            name='savings_doc',
            field=models.FilePathField(null=True),
        ),
        migrations.CreateModel(
            name='Landlord_Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('is_landlord', models.BooleanField(choices=[(True, 'Landlord'), (False, 'Tenant')], default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
