# Generated by Django 3.0.2 on 2020-02-14 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_auto_20200213_2312'),
    ]

    operations = [
        migrations.RenameField(
            model_name='landlord_profile',
            old_name='user',
            new_name='landlord',
        ),
        migrations.RenameField(
            model_name='tenant_profile',
            old_name='user',
            new_name='tenant',
        ),
    ]
