# Generated by Django 3.0.2 on 2020-02-14 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_tenant_reviews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant_reviews',
            name='landlord',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Landlord_Profile'),
        ),
        migrations.AlterField(
            model_name='tenant_reviews',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Tenant_Profile'),
        ),
    ]
