# Generated by Django 3.0.3 on 2020-04-20 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_auto_20200413_1409'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landlord_profile',
            name='test',
        ),
        migrations.AddField(
            model_name='landlord_profile',
            name='county',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='landlord_profile',
            name='identification',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='landlord_profile',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='profile_pics'),
        ),
        migrations.AddField(
            model_name='landlord_profile',
            name='postCode',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='landlord_profile',
            name='street1',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='landlord_profile',
            name='street2',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='tenant_profile',
            name='hapDocument',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='tenant_profile',
            name='identification',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='tenant_profile',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='profile_pics'),
        ),
        migrations.AddField(
            model_name='tenant_profile',
            name='references',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='tenant_profile',
            name='salaryDocument',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='tenant_profile',
            name='savingsDocument',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
