# Generated by Django 2.2 on 2020-04-21 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_auto_20200421_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant_profile',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='profile_pics'),
        ),
    ]
