# Generated by Django 2.2 on 2020-04-21 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0032_auto_20200421_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landlord_profile',
            name='image',
            field=models.ImageField(default='profile_pics/default/default.jpg', upload_to='profile_pics'),
        ),
        migrations.AlterField(
            model_name='tenant_profile',
            name='image',
            field=models.ImageField(default='profile_pics/default/default.jpg', upload_to='profile_pics'),
        ),
    ]
