# Generated by Django 2.2 on 2020-04-21 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0033_auto_20200421_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant_profile',
            name='savingsDocument',
            field=models.FileField(blank=True, null=True, upload_to='docs'),
        ),
    ]
