# Generated by Django 3.2.6 on 2021-08-27 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0034_auto_20200421_1415'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenant_profile',
            name='savings',
        ),
        migrations.AddField(
            model_name='tenant_profile',
            name='both_salary',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='landlord_profile',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='profile_pics'),
        ),
        migrations.AlterField(
            model_name='tenant_profile',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='profile_pics'),
        ),
        migrations.CreateModel(
            name='Guarantor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('g_salary', models.FloatField(null=True)),
                ('g_salaryDoc', models.FileField(blank=True, null=True, upload_to='docs')),
                ('g_confirmation', models.FileField(blank=True, null=True, upload_to='docs')),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.tenant_profile')),
            ],
        ),
    ]
