# Generated by Django 3.2.6 on 2021-08-27 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0035_auto_20210827_0924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant_profile',
            name='is_hap',
            field=models.NullBooleanField(),
        ),
    ]
