# Generated by Django 2.2.4 on 2019-11-13 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='landlord',
            old_name='landloard_first',
            new_name='landlord_first',
        ),
        migrations.RenameField(
            model_name='landlord',
            old_name='landloard_last',
            new_name='landlord_last',
        ),
    ]
