# Generated by Django 3.0.3 on 2020-05-07 13:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import projects.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Properties',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street1', models.CharField(max_length=30, null=True)),
                ('street2', models.CharField(max_length=30, null=True)),
                ('county', models.CharField(choices=[('Antrim', 'Antrim'), ('Armagh', 'Armagh'), ('Carlow', 'Carlow'), ('Cavan', 'Cavan'), ('Clare', 'Clare'), ('Cork', 'Cork'), ('Derry', 'Derry'), ('Donegal', 'Donegal'), ('Down', 'Down'), ('Dublin', 'Dublin'), ('Fermanagh', 'Fermanagh'), ('Galway', 'Galway'), ('Galway', 'Galway'), ('Kerry', 'Kerry'), ('Kildare', 'Kildare'), ('Kilkenny', 'Kilkenny'), ('Laois', 'Laois'), ('Leitrim', 'Leitrim'), ('Limerick', 'Limerick'), ('Longford', 'Longford'), ('Louth', 'Louth'), ('Mayo', 'Mayo'), ('Meath', 'Meath'), ('Monaghan', 'Monaghan'), ('Offaly', 'Offaly'), ('Roscommon', 'Roscommon'), ('Sligo', 'Sligo'), ('Tipperary', 'Tipperary'), ('Tyrone', 'Tyrone'), ('Waterford', 'Waterford'), ('Westmeath', 'Westmeath'), ('Wexford', 'Wexford'), ('Wicklow', 'Wicklow')], max_length=200)),
                ('rentPrice', models.IntegerField(verbose_name='Cost of rent per month')),
                ('description', models.TextField(null=True)),
                ('type', models.CharField(choices=[('House', 'House'), ('Apartment', 'Apartment'), ('Office', 'Office'), ('Industrial', 'Industrial')], default='House', max_length=200, verbose_name='Type of property')),
                ('bedRooms', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8)], default=1, verbose_name='No. Bedrooms')),
                ('bathRoom', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8)], default=1, verbose_name='No. Bathrooms')),
                ('tenantSalary', models.IntegerField(null=True, verbose_name='Tenant expected salary')),
                ('referenceRequired', models.BooleanField(default=False, verbose_name='Reference required?')),
                ('image', models.FileField(default=None, upload_to='house_preview/', verbose_name='Select an image that describes this property best')),
                ('listingStatus', models.BooleanField(default=True, verbose_name='Do you want to pause your listing?')),
                ('landlord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule_Viewing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=16, null=True)),
                ('time', models.CharField(max_length=6, null=True)),
                ('landlord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Landlord_Profile', to_field='landlord')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Properties')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Tenant_Profile', to_field='tenant')),
            ],
        ),
        migrations.CreateModel(
            name='Property_Reviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_description', models.TextField()),
                ('landlord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Landlord_Profile', to_field='landlord')),
                ('property', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='projects.Properties')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Tenant_Profile', to_field='tenant')),
            ],
        ),
        migrations.CreateModel(
            name='Property_Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.FileField(default=None, upload_to=projects.models.get_property_image_filenames, verbose_name='Select property images')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Properties')),
            ],
        ),
        migrations.CreateModel(
            name='Property_Applications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_description', models.TextField(default='app description')),
                ('created', models.TextField(default=1)),
                ('viewing_scheduled', models.BooleanField(default=False)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Properties')),
                ('property_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Landlord_Profile', to_field='landlord')),
                ('tenant_apply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Tenant_Profile', to_field='tenant')),
            ],
        ),
    ]
