# Generated by Django 3.0.2 on 2020-02-03 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='title',
            new_name='address',
        ),
        migrations.RemoveField(
            model_name='project',
            name='technology',
        ),
        migrations.AddField(
            model_name='project',
            name='bathRoom',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='bedRooms',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='rentPrice',
            field=models.IntegerField(default=759),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='tenantCondtions',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
