# Generated by Django 3.0.2 on 2020-02-05 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_listing_database'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.RenameField(
            model_name='listing_database',
            old_name='user_id',
            new_name='user',
        ),
    ]
