# Generated by Django 3.0.2 on 2020-02-05 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_remove_listing_database_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing_Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default.jpg', upload_to='house_preview')),
            ],
        ),
        migrations.RemoveField(
            model_name='listing_database',
            name='image',
        ),
    ]
