# Generated by Django 3.0.2 on 2020-02-05 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_auto_20200205_2312'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing_images',
            name='listingId',
            field=models.ManyToManyField(to='projects.Listing_Database'),
        ),
    ]
