# Generated by Django 3.0.2 on 2020-02-06 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_auto_20200206_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing_database',
            name='image',
            field=models.ImageField(upload_to='house_preview/'),
        ),
    ]
