# Generated by Django 3.0.2 on 2020-02-10 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_auto_20200205_1901'),
        ('projects', '0015_auto_20200206_1105'),
    ]

    operations = [
    ]
