# Generated by Django 3.0.2 on 2020-02-08 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_listing_database_user'),
        ('projects', '0008_auto_20200205_1901'),
    ]

    operations = [
    ]
