# Generated by Django 3.0.2 on 2020-02-10 11:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0016_merge_20200210_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing_database',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='listing_database',
            name='image',
            field=models.ImageField(upload_to='house_preview/'),
        ),
    ]
