# Generated by Django 3.0.2 on 2020-02-08 16:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0017_merge_20200208_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing_database',
            name='image',
            field=models.ImageField(upload_to='house_preview/'),
        ),
        migrations.AlterField(
            model_name='listing_database',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
