# Generated by Django 3.0.2 on 2020-02-09 22:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0018_auto_20200208_1655'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing_Replies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Listing_Database_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Listing_Database')),
            ],
        ),
    ]
