# Generated by Django 3.0.2 on 2020-02-12 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0019_listing_replies'),
        ('projects', '0017_auto_20200210_1125'),
    ]

    operations = [
    ]
