# Generated by Django 3.0.2 on 2020-02-13 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0022_auto_20200213_2320'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property_applications',
            name='listingId',
        ),
    ]
