# Generated by Django 3.0.2 on 2020-02-13 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0023_remove_property_applications_listingid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property_applications',
            name='user',
        ),
    ]
