# Generated by Django 3.0.2 on 2020-02-13 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0024_remove_property_applications_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Property_Applications',
        ),
    ]
