# Generated by Django 3.0.2 on 2020-02-13 23:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0026_auto_20200213_2346'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Properties',
            new_name='Properties1',
        ),
        migrations.CreateModel(
            name='Property_Applications1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
