# Generated by Django 3.0.2 on 2020-02-14 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0029_property_reviews'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property_reviews',
            name='landlord',
        ),
        migrations.AddField(
            model_name='property_reviews',
            name='property',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='projects.Properties'),
        ),
    ]
