# Generated by Django 3.0.3 on 2020-04-20 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_auto_20200420_1037'),
        ('projects', '0032_auto_20200413_1409'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property_reviews',
            old_name='review',
            new_name='review_description',
        ),
        migrations.RemoveField(
            model_name='properties',
            name='address',
        ),
        migrations.RemoveField(
            model_name='properties',
            name='tenantCondtions',
        ),
        migrations.RemoveField(
            model_name='property_reviews',
            name='created',
        ),
        migrations.AddField(
            model_name='properties',
            name='county',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='properties',
            name='referenceRequired',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='properties',
            name='street1',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='properties',
            name='street2',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='properties',
            name='tenantSalary',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='properties',
            name='tenantSavings',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='properties',
            name='bathRoom',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='properties',
            name='bedRooms',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='properties',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='property_applications',
            name='property_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Landlord_Profile', to_field='landlord'),
        ),
        migrations.AlterField(
            model_name='property_applications',
            name='tenant_apply',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Tenant_Profile', to_field='tenant'),
        ),
        migrations.AlterField(
            model_name='property_reviews',
            name='landlord',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Landlord_Profile', to_field='landlord'),
        ),
        migrations.AlterField(
            model_name='property_reviews',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Tenant_Profile', to_field='tenant'),
        ),
        migrations.CreateModel(
            name='Schedule_Viewing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=16, null=True)),
                ('time', models.CharField(max_length=6, null=True)),
                ('landlord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Landlord_Profile', to_field='landlord')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Properties')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Tenant_Profile', to_field='tenant')),
            ],
        ),
    ]
