# Generated by Django 3.0.3 on 2020-04-20 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0033_auto_20200420_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='properties',
            name='bathRoom',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=1),
        ),
        migrations.AlterField(
            model_name='properties',
            name='bedRooms',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=1),
        ),
        migrations.AlterField(
            model_name='properties',
            name='county',
            field=models.IntegerField(choices=[(1, 'Antrim'), (2, 'Armagh'), (3, 'Carlow'), (4, 'Cavan'), (5, 'Clare'), (6, 'Cork'), (7, 'Derry'), (8, 'Donegal'), (9, 'Down'), (10, 'Dublin'), (11, 'Fermanagh'), (12, 'Galway'), (13, 'Kerry'), (14, 'Kildare'), (15, 'Kilkenny'), (16, 'Laois'), (17, 'Leitrim'), (18, 'Limerick'), (19, 'Longford'), (20, 'Louth'), (21, 'Mayo'), (22, 'Meath'), (23, 'Monaghan'), (24, 'Offaly'), (25, 'Roscommon'), (26, 'Sligo'), (27, 'Tipperary'), (28, 'Tyrone'), (29, 'Waterford'), (30, 'Westmeath'), (31, 'Wexford'), (32, 'Wicklow')], default=1),
        ),
    ]
