# Generated by Django 3.0.3 on 2020-04-20 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0034_auto_20200420_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='properties',
            name='bathRoom',
            field=models.IntegerField(choices=[(1, 1), (1, 2)], default=1),
        ),
        migrations.AlterField(
            model_name='properties',
            name='bedRooms',
            field=models.IntegerField(choices=[(1, 1), (1, 2)], default=1),
        ),
        migrations.AlterField(
            model_name='properties',
            name='county',
            field=models.CharField(choices=[('Antrim', 'Antrim'), ('Cavan', 'Dublin')], default=1, max_length=200),
        ),
    ]
