# Generated by Django 3.2.6 on 2021-08-27 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_merge_20200210_1045'),
        ('projects', '0037_auto_20200420_1512'),
    ]

    operations = [
    ]
