# Generated by Django 3.2.6 on 2021-08-27 07:24

from django.db import migrations, models
import django.db.models.deletion
import projects.models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0038_merge_20210827_0920'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='properties',
            name='tenantSavings',
        ),
        migrations.AddField(
            model_name='properties',
            name='listingStatus',
            field=models.BooleanField(default=True, verbose_name='Do you want to pause your listing?'),
        ),
        migrations.AddField(
            model_name='property_applications',
            name='viewing_scheduled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='properties',
            name='bathRoom',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8)], default=1, verbose_name='No. Bathrooms'),
        ),
        migrations.AlterField(
            model_name='properties',
            name='bedRooms',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8)], default=1, verbose_name='No. Bedrooms'),
        ),
        migrations.AlterField(
            model_name='properties',
            name='image',
            field=models.FileField(default=None, upload_to='house_preview/', verbose_name='Select an image that describes this property best'),
        ),
        migrations.AlterField(
            model_name='properties',
            name='referenceRequired',
            field=models.BooleanField(default=False, verbose_name='Reference required?'),
        ),
        migrations.AlterField(
            model_name='properties',
            name='rentPrice',
            field=models.IntegerField(verbose_name='Cost of rent per month'),
        ),
        migrations.AlterField(
            model_name='properties',
            name='street1',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='properties',
            name='street2',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='properties',
            name='tenantSalary',
            field=models.IntegerField(null=True, verbose_name='Tenant expected salary'),
        ),
        migrations.AlterField(
            model_name='properties',
            name='type',
            field=models.CharField(choices=[('House', 'House'), ('Apartment', 'Apartment'), ('Office', 'Office'), ('Industrial', 'Industrial')], default='House', max_length=200, verbose_name='Type of property'),
        ),
        migrations.CreateModel(
            name='Property_Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.FileField(default=None, upload_to=projects.models.get_property_image_filenames, verbose_name='Select property images')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.properties')),
            ],
        ),
    ]
